create table sisyphus_uac.s_uac_user
(
    id                  bigint auto_increment comment 'ID'
        primary key,
    version             int          default 0                 null comment 'version',
    gender              int          default 0                 null comment 'gender',
    login_name          varchar(50)  default ''                null comment 'login_name',
    login_pwd           varchar(300) default ''                null comment 'login_password',
    user_code           varchar(32)  default ''                null comment 'user_code',
    user_name           varchar(50)  default ''                null comment 'user_name',
    phone               varchar(15)  default ''                null comment 'phone',
    email               varchar(50)  default ''                null comment 'email',
    status              varchar(20)  default ''                null comment 'status: enable able',
    user_source         varchar(32)  default ''                null comment 'user_source: from where? app? browser? ',
    type                varchar(32)  default ''                null comment 'type stuff? customer?',
    last_login_ip       varchar(20)  default ''                null comment 'last_login_ip',
    last_login_location varchar(50)  default ''                null comment 'last_login_location',
    remark              varchar(300) default ''                null comment 'remark',
    last_login_time     datetime                               null comment 'last_login_time',
    pwd_error_count     smallint     default 0                 null comment 'pwd_error_count',
    pwd_error_time      datetime                               null comment 'time of last error password',
    creator                varchar(20)                default ''                null comment 'creator',
    creator_id             bigint                                               null comment 'creator id',
    gmt_created            datetime                   default CURRENT_TIMESTAMP null comment 'create time',
    last_operator          varchar(20)                default ''                null comment 'modifier',
    last_operator_id       bigint                                               null comment 'modifier id',
    gmt_modified           datetime                   default CURRENT_TIMESTAMP null comment 'modify time',
    is_deleted             int                        default 0                 null comment 'deleted or not'
    avatar              varchar(20)  default ''                null
)
    comment 'user' charset = utf8;

INSERT INTO sisyphus_uac.s_uac_user (id, version, gender, login_name, login_pwd, user_code, user_name, phone, email, status, user_source, type, last_login_ip, last_login_location, remark, last_login_time, pwd_error_count, pwd_error_time, creator, creator_id, gmt_created, last_operator, last_operator_id, gmt_modified, is_deleted, avatar) VALUES (1, 1, 1, 'admin', '$2a$10$cqWFplRx3tdlqta2E4/WC.01fpWNEWJPcOkFi1XHG4Q7aV8xKU77m', 'admin', 'admin', '07536967374', 'zzhao84@sheffield.ac.uk', 'enable', '', '1', '127.0.0.1', '', '', '2022-03-01 19:59:31', 0, null, '', null, '2022-02-28 06:49:29', '', null, null, 0, '');
INSERT INTO sisyphus_uac.s_uac_user (id, version, gender, login_name, login_pwd, user_code, user_name, phone, email, status, user_source, type, last_login_ip, last_login_location, remark, last_login_time, pwd_error_count, pwd_error_time, creator, creator_id, gmt_created, last_operator, last_operator_id, gmt_modified, is_deleted, avatar) VALUES (2, 1, 1, 'zard', '$2a$10$cqWFplRx3tdlqta2E4/WC.01fpWNEWJPcOkFi1XHG4Q7aV8xKU77m', 'A', 'A', '07536967374', 'zzhao84@sheffield.ac.uk', 'enable', '', '2', '', '', '', null, 0, null, '', null, '2022-03-01 21:38:38', '', null, '2022-03-01 21:38:38', 0, '');
INSERT INTO sisyphus_uac.s_uac_user (id, version, gender, login_name, login_pwd, user_code, user_name, phone, email, status, user_source, type, last_login_ip, last_login_location, remark, last_login_time, pwd_error_count, pwd_error_time, creator, creator_id, gmt_created, last_operator, last_operator_id, gmt_modified, is_deleted, avatar) VALUES (3, 1, 1, 'zard98', '$2a$10$cqWFplRx3tdlqta2E4/WC.01fpWNEWJPcOkFi1XHG4Q7aV8xKU77m', 'B', 'B', '07536967374', 'zzhao84@sheffield.ac.uk', 'enable', '', '3', '', '', '', null, 0, null, '', null, '2022-03-01 21:38:58', '', null, '2022-03-01 21:38:58', 0, '');
INSERT INTO sisyphus_uac.s_uac_user (id, version, gender, login_name, login_pwd, user_code, user_name, phone, email, status, user_source, type, last_login_ip, last_login_location, remark, last_login_time, pwd_error_count, pwd_error_time, creator, creator_id, gmt_created, last_operator, last_operator_id, gmt_modified, is_deleted, avatar) VALUES (4, 1, 2, 'eden', '$2a$10$cqWFplRx3tdlqta2E4/WC.01fpWNEWJPcOkFi1XHG4Q7aV8xKU77m', 'C', 'C', '07536967374', 'zzhao84@sheffield.ac.uk', 'enable', '', '2', '', '', '', null, 0, null, '', null, '2022-03-01 21:45:30', '', null, '2022-03-01 21:45:30', 0, '');
INSERT INTO sisyphus_uac.s_uac_user (id, version, gender, login_name, login_pwd, user_code, user_name, phone, email, status, user_source, type, last_login_ip, last_login_location, remark, last_login_time, pwd_error_count, pwd_error_time, creator, creator_id, gmt_created, last_operator, last_operator_id, gmt_modified, is_deleted, avatar) VALUES (5, 1, 1, 'eden98', '$2a$10$cqWFplRx3tdlqta2E4/WC.01fpWNEWJPcOkFi1XHG4Q7aV8xKU77m', 'D', 'D', '07536967374', 'zzhao84@sheffield.ac.uk', 'enable', '', '3', '', '', '', null, 0, null, '', null, '2022-03-01 21:45:30', '', null, '2022-03-01 21:45:30', 0, '');
INSERT INTO sisyphus_uac.s_uac_user (id, version, gender, login_name, login_pwd, user_code, user_name, phone, email, status, user_source, type, last_login_ip, last_login_location, remark, last_login_time, pwd_error_count, pwd_error_time, creator, creator_id, gmt_created, last_operator, last_operator_id, gmt_modified, is_deleted, avatar) VALUES (6, 1, 2, 'jack', '$2a$10$cqWFplRx3tdlqta2E4/WC.01fpWNEWJPcOkFi1XHG4Q7aV8xKU77m', 'E', 'E', '07536967374', 'zzhao84@sheffield.ac.uk', 'enable', '', '3', '', '', '', null, 0, null, '', null, '2022-03-01 22:49:48', '', null, '2022-03-01 22:49:48', 0, '');
INSERT INTO sisyphus_uac.s_uac_user (id, version, gender, login_name, login_pwd, user_code, user_name, phone, email, status, user_source, type, last_login_ip, last_login_location, remark, last_login_time, pwd_error_count, pwd_error_time, creator, creator_id, gmt_created, last_operator, last_operator_id, gmt_modified, is_deleted, avatar) VALUES (7, 1, 1, 'jack98', '$2a$10$cqWFplRx3tdlqta2E4/WC.01fpWNEWJPcOkFi1XHG4Q7aV8xKU77m', 'F', 'F', '07536967374', 'zzhao84@sheffield.ac.uk', 'enable', '', '2', '', '', '', null, 0, null, '', null, '2022-03-01 22:50:10', '', null, '2022-03-01 22:50:10', 0, '');
INSERT INTO sisyphus_uac.s_uac_user (id, version, gender, login_name, login_pwd, user_code, user_name, phone, email, status, user_source, type, last_login_ip, last_login_location, remark, last_login_time, pwd_error_count, pwd_error_time, creator, creator_id, gmt_created, last_operator, last_operator_id, gmt_modified, is_deleted, avatar) VALUES (8, 1, 1, 'zzhao', '$2a$10$cqWFplRx3tdlqta2E4/WC.01fpWNEWJPcOkFi1XHG4Q7aV8xKU77m', 'G', 'G', '07536967374', 'zzhao84@sheffield.ac.uk', 'enable', '', '3', '', '', '', null, 0, null, '', null, '2022-03-01 22:50:32', '', null, '2022-03-01 22:50:32', 0, '');
INSERT INTO sisyphus_uac.s_uac_user (id, version, gender, login_name, login_pwd, user_code, user_name, phone, email, status, user_source, type, last_login_ip, last_login_location, remark, last_login_time, pwd_error_count, pwd_error_time, creator, creator_id, gmt_created, last_operator, last_operator_id, gmt_modified, is_deleted, avatar) VALUES (9, 1, 2, 'zzhao98', '$2a$10$cqWFplRx3tdlqta2E4/WC.01fpWNEWJPcOkFi1XHG4Q7aV8xKU77m', 'H', 'H', '07536967374', 'zzhao84@sheffield.ac.uk', 'enable', '', '3', '', '', '', null, 0, null, '', null, '2022-03-01 22:51:02', '', null, '2022-03-01 22:51:02', 0, '');
INSERT INTO sisyphus_uac.s_uac_user (id, version, gender, login_name, login_pwd, user_code, user_name, phone, email, status, user_source, type, last_login_ip, last_login_location, remark, last_login_time, pwd_error_count, pwd_error_time, creator, creator_id, gmt_created, last_operator, last_operator_id, gmt_modified, is_deleted, avatar) VALUES (10, 2, 1, 'zard0214', '$2a$10$cqWFplRx3tdlqta2E4/WC.01fpWNEWJPcOkFi1XHG4Q7aV8xKU77m', 'I', '1d1ddwqcwqcqw', '07536967374', 'zzhao84@sheffield.ac.uk', 'enable', '', '2', '', '', '', null, 0, null, '', null, '2022-03-01 22:51:47', '', null, '2022-03-01 22:51:47', 0, '');