version: "3.1"
services:
  seata-server:
    image: seataio/seata-server:1.4.2
    container_name: seata-server-1.4.2
    ports:
      - "8091:8091"
    # file、db、redis
    environment:
      - SEATA_PORT=8091
      - STORE_MODE=file
      - SEATA_IP=127.0.0.1