#version: '2'
#services:
#  zoo1:
#    image: wurstmeister/zookeeper
#    restart: unless-stopped
#    hostname: zoo1
#    ports:
#      - "2181:2181"
#    container_name: zookeeper
#  kafka:
#    image: wurstmeister/kafka
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: host.docker.internal
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9092
#      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
#      KAFKA_ADVERTISED_PORT: 9092
#      KAFKA_BROKER_ID: 2
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#    depends_on:
#      - zoo1
#    container_name: kafka
#  kafka-manager:
#    image: sheepkiller/kafka-manager
#    environment:
#      ZK_HOSTS: host.docker.internal
#    ports:
#      - "9000:9000"
#
## sh kafka-server-start.sh ../config/server.properties
## /usr/local/Cellar/kafka/2.8.0/bin
## kafka-topics.sh --create --topic test --zookeeper zoo1:2181 --replication-factor 1 --partitions 1
## bin % kafka-topics --list --zookeeper localhost:2181
#
